name: tooling_lecture_2019
dependencies:
  - python=3.6
  - tensorflow>=2.0.0
  - numpy>=1.15.4
  - pytest>=3.10.0
  - pytest-cov>=2.6.0
  - pytest-pep8>=1.0.6
  - scikit-learn>=0.21.3
  - pip:
    - ray>=0.7.6